/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-My_React_Project-mcOEXMNrb8n57pQA35nMQaP-wn3OlL5U",
  "version": "2020-11-20"
}

export default ebconfig;
